### ISSUE TITLE
Expresiones lógicas

### ISSUE THREAD

**Issue by Paola939** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-isaias-paola-ariadna-arisbeth#1]
[practica de loguica proposicional.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-isaias-paola-ariadna-arisbeth/files/13608350/practica.de.loguica.proposicional.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
